apiVersion: apps/v1
kind: Deployment
metadata:
  name: oilapp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: oilapp-operator
  template:
    metadata:
      labels:
        name: oilapp-operator
    spec:
      serviceAccountName: oilapp-operator
      containers:
        - name: oilapp-operator
          # Replace this with the built image name
          image: hmxq.top/oilapp-operator
          command:
          - oilapp-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "oilapp-operator"
